# Config spring
server:
  port: 8081
  servlet:
    context-path: /auth

mysql:
  host: root
  username: root
  password:

# Config database
spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:3306/db_ecommerce?createDatabaseIfNotExist=true
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Config project
url-internal-service:
  api-gateway: http://localhost:8181

# Config eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Active all end-point in actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

demo:
  message: This is test development